### ISSUE TITLE
Allow multiple game versions

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/mrpm#1]
Some plugins or mods will also work even if they have no version available for a specific game version. Therefore, it should be possible to set a range or something as target game version.

### Example
```toml
game_version = "1.21.4"
# or
game_version = ["1.21.4" , "1.21.5"]
```
